## configuration for https://travis-ci.org/mrmx/opencryptos-java
sudo: false
dist: xenial
language: java
jdk:
  - oraclejdk7
  - openjdk8  
  - openjdk9
  - openjdk11
install: true
script:
  - mvn clean package